logger:
  level: INFO
  format: console # json, console

http:
  port: 8080

ratelimit:
  driver: memory # memory, redis
  limit: 6000
  frequency: 10s
  redis_option:
    host: localhost
    port: 6379
    db: 1
    max_retry: 1000
    